---
- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False
  tags: [newrelic-php]

- name: Check for newrelic_appname
  fail:
    msg: "newrelic_appname has not been defined"
  when: newrelic_appname|default(False) == False
  tags: [newrelic-php]

- include: trusty.yml
  when: ansible_distribution_release == 'trusty'
  tags: [newrelic-php]

- include: default.yml
  when: newrelic_loaded_os_family|default(False) == False
  tags: [newrelic-php]



