---

- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Default | Check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported"
  when: supported_os_family|default(False) == False


- name: Default | Check for unsupported target operating system
  fail:
    msg: "The operating system of the target machine ({{ inventory_hostname }}) is not currently supported"
  when: supported_os_family|default(False) == False


- name: Check for newrelic_license_key
  fail:
    msg: "newrelic_license_key has not been defined"
  when: newrelic_license_key|default(False) == False
  tags: [newrelic-php]

- name: Check for newrelic_appname
  fail:
    msg: "newrelic_appname has not been defined"
  when: newrelic_appname|default(False) == False
  tags: [newrelic-php]

- name: Check for PHP-FPM
  command: "apachectl -M"
  changed_when: false
  check_mode: no
  register: _apache_modules
  become: true

- name: Set fact for PHP-FPM
  set_fact:
     php_fpm_loaded: true
  when: _apache_modules.stdout.find('php5-fpm') != -1

- include: configure-Debian.yml
  when: ansible_os_family == 'Debian'
  tags: [newrelic-php]

